# ethernet interface
# docker_ethernet_interface: eth0
home_lan_interface: eth0

ansible_become_pass: "{{ vault_ansible_become_pass }}"
ansible_user_first_run: root
ansible_pass_first_run: "{{ vault_ansible_become_pass }}"

app_data_root: /mnt/storage
media_root: /mnt/storage

host_local: kazan

private_ip: "{{ server_ns.ip }}"

enable_wifi: false

create_docker_iot_network: false
create_docker_dmz_network: false
create_docker_home_lan_network: false
create_docker_mariadb_network: false

security_ssh_port: "{{ ssh_port }}"
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
security_ssh_allowed_users:
  - "{{ user.name }}"
security_sshd_state: started
security_ssh_restart_handler_state: restarted
security_sudoers_passwordless:
  - "{{ user.name }}"
security_autoupdate_enabled: true
security_autoupdate_blacklist: []
security_autoupdate_reboot: true
security_autoupdate_reboot_time: 03:00
security_fail2ban_enabled: true
