- name: Restart homer
  community.docker.docker_container:
    name: homer
    state: started
    restart: true
  when: enable_homer | default(false) and homer_exists is defined and homer_running is defined
