- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  loop: "{{ syncthing_dirs }}"
  become: true
  when: host_enable_syncthing | default(false)

- name: Make sure the syncthing container is created and running
  when: host_enable_syncthing | default(false)
  community.docker.docker_container:
    name: syncthing
    image: lscr.io/linuxserver/syncthing:{{ syncthing_version }}
    pull: true
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ docker_user.id }}"
      PGID: "{{ docker_user.id }}"
    networks: "{{ host_syncthing_networks | default([{}]) }}"
    exposed_ports: "{{ host_syncthing_ports | default([]) }}"
    hostname: "{{ host_server_syncthing_hostname }}"
    state: started
    volumes: "{{ host_syncthing_volumes }}"
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      # routers // ui
      traefik.http.routers.syncthing-ui.rule: Host(`{{ host_syncthing_url }}`)
      traefik.http.routers.syncthing-ui.service: syncthing-ui
      # services
      traefik.http.services.syncthing-ui.loadbalancer.server.port: "8384"
      # traefik.http.services.syncthing-sync.loadbalancer.server.port: "22000"
      # traefik.http.services.syncthing-sync-udp.loadbalancer.server.port: 21027/udp
      # middlewares
      traefik.http.middlewares.syncthing-ui-ratelimit.ratelimit.average: "5"
      traefik.http.middlewares.syncthing-ui-ratelimit.ratelimit.burst: "1000"
      traefik.http.middlewares.syncthing-ui-compress.compress: "true"
      # middlewares for routers
      traefik.http.routers.syncthing-ui.middlewares: syncthing-ui-ratelimit,syncthing-ui-compress
    restart_policy: unless-stopped
