- name: Restart deluge
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: started
    restart: true
  when: enable_deluge | default(false) and deluge_exists is defined and deluge_running is defined
