- name: restart traefik
  ansible.builtin.docker_compose:
    project_src: "{{ traefik_install_dir }}"
    restarted: true

- name: restart docker proxy
  docker_container:
    name: docker_proxy
    state: started
    restart: true
  when: enable_docker_proxy | default(false) and docker_proxy_exists is defined and docker_proxy_running is defined
