- name: Restart traefik
  community.docker.docker_container:
    name: traefik
    state: started
    restart: true
  when: enable_traefik | default(false) and traefik_exists is defined and traefik_running is defined

- name: Restart docker proxy
  community.docker.docker_container:
    name: docker_proxy
    state: started
    restart: true
  when: traefik_enable_docker_proxy | default(false) and docker_proxy_exists is defined and traefik_docker_proxy_running is defined
