container_name: vaultwarden  # noqa: var-naming[no-role-prefix]
homer_category: Services  # noqa: var-naming[no-role-prefix]
dashboard_name: Vaultwarden  # noqa: var-naming[no-role-prefix]
logo: assets/tools/bitwarden.png  # noqa: var-naming[no-role-prefix]
subtitle: Password manager  # noqa: var-naming[no-role-prefix]
tag: app  # noqa: var-naming[no-role-prefix]
url: https://vaultwarden.{{ host }}  # noqa: var-naming[no-role-prefix]
