ansible_become_pass: "{{ vault_ansible_become_pass }}"
ansible_user_first_run: root
ansible_pass_first_run: "{{ vault_ansible_become_pass }}"

app_data_root: /mnt/storage
media_root: /mnt/storage

private_ip: "{{ server_ns.ip }}"

physical_netowrk_interface: eth0
