- name: Include vault
  ansible.builtin.include_vars: vault.yml

- name: Create app directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  loop: "{{ vaultwarden_dirs }}"
  become: true

- name: Create install directory
  ansible.builtin.file:
    path: /opt/vaultwarden
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install compose file
  ansible.builtin.template:
    src: files/docker-compose.yml
    dest: /opt/vaultwarden/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: Restart vaultwarden
  become: true
