- name: Include vault
  ansible.builtin.include_vars: vault.yml

- name: Create plex directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  loop:
    - "{{ plex_dirs }}"
    - "{{ plex_media_dirs }}"
  become: true

- name: Get infos on the plex container
  community.docker.docker_container_info:
    name: plex
  register: plex_docker_status

- name: Does plex container exist?
  ansible.builtin.set_fact:
    plex_exists: true
  when: plex_docker_status.exists

- name: Is docker container running?
  ansible.builtin.set_fact:
    plex_running: true
  when: plex_exists is defined and plex_docker_status.container['State']['Running']

- name: Make sure the plex container is created and running
  when: enable_plex | default(false)
  community.docker.docker_container:
    name: plex
    image: lscr.io/linuxserver/plex:{{ plex_version }}
    pull: true
    env:
      PUID: "3000"
      PGID: "3000"
      TZ: "{{ timezone }}"
      PLEX_CLAIM: "{{ plex_claim }}"
      VERSION: docker
    networks:
      - name: traefik
      - name: home_lan
        ipv4_address: "{{ plex.ip }}"
    hostname: server-plex
    state: started
    volumes:
      - "{{ plex_library_dir }}:/config"
      - "{{ plex_transcode_dir }}:/transcode"
      - "{{ plex_tvseries_dir }}:/tvseries"
      - "{{ plex_movies_dir }}:/movies"
      - "{{ plex_music_dir }}:/music"
      - "{{ plex_photos_dir }}:/photos"
      - "{{ plex_videos_dir }}:/videos"
    devices:
      - /dev/dri:/dev/dri
    restart_policy: unless-stopped
