create_user: true
install_packages: true
modify_barhrc: true
remove_snap: true
update_packages: true
update_ssh: true

packages_to_install:
  - speedtest-cli
  - htop
  - git
  - vim
  - neofetch
  - rsync
  - sudo

ssh_extra_allowed_users: "{{ user }}"
