- name: Include vault
  ansible.builtin.include_vars: vault.yml

- name: Create directories
  ansible.builtin.include_tasks: directories.yml
  when: homeassistant_create_directories | default(false)

- name: Prepare kvm
  ansible.builtin.include_tasks: kvm.yml
  when: homeassistant_prepare_kvm | default(false)

- name: Create network bridge
  ansible.builtin.include_tasks: bridge.yml
  when: homeassistant_create_bridge | default(false)

- name: Download hassio image
  ansible.builtin.include_tasks: image.yml
  when: homeassistant_download_image | default(false)

- name: Create hassio virtual machine
  ansible.builtin.include_tasks: vm.yml
  when: homeassistant_create_vm | default(false)
