- name: Include vault
  ansible.builtin.include_vars: vault.yml

- name: Include variables
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_items:
    - defaults/code-server.yml
    - defaults/esphome.yml
    - defaults/homeassistant.yml
    - defaults/mariadb.yml
    - defaults/mosquitto.yml
  when: enable_homeassistant | default(false)

- name: mariadb
  ansible.builtin.include_tasks: mariadb.yml
  when: enable_mariadb | default(false)

- name: esphome
  ansible.builtin.include_tasks: esphome.yml
  when: enable_esphome | default(false)

- name: code-server
  ansible.builtin.include_tasks: code-server.yml
  when: enable_code_server | default(false)

- name: mosquitto
  ansible.builtin.include_tasks: mosquitto.yml
  when: enable_mosquitto | default(false)

- name: homeassistant
  ansible.builtin.include_tasks: homeassistant.yml
  when: enable_homeassistant | default(false)
