- name: Create homeassistant app directory
  ansible.builtin.file:
    path: "{{ mariadb_database_dir }}"
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  become: true

- name: Make sure the mariadb container is created and running
  when: enable_mariadb | default(false)
  community.docker.docker_container:
    name: mariadb
    image: mariadb:{{ mariadb_version }}
    pull: true
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - name: traefik
    user: "{{ docker_user.id }}:{{ docker_user.id }}"
    volumes:
      - "{{ mariadb_database_dir }}/:/var/lib/mysql"
      - /etc/localtime:/etc/localtime:ro
    env:
      TZ: "{{ timezone }}"
      MYSQL_PASSWORD: "{{ homeassistant_mariadb_password }}"
      MYSQL_DATABASE: "{{ homeassistant_mariadb_database }}"
      MYSQL_USER: "{{ homeassistant_mariadb_user }}"
      MYSQL_ROOT_PASSWORD: "{{ mariadb_root_password }}"
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      # routers
      traefik.tcp.routers.mariadb.rule: HostSNI(`*`)
      traefik.tcp.routers.mariadb.entrypoints: mariadb
      traefik.tcp.routers.mariadb.service: mariadb-svc
      traefik.tcp.services.mariadb-svc.loadbalancer.server.port: "{{ mariadb_port }}"
    hostname: mariadb
    state: started
    restart_policy: unless-stopped
