- name: Get info on virtual machine
  ansible.builtin.command:
    cmd: virsh list --all
  register: homeassistant_vminfo
  changed_when: false

- name: Check if vm exists
  ansible.builtin.set_fact:
    homeassistant_vm_exists: true
  when: homeassistant_vm_name in homeassistant_vminfo.stdout

- name: Create virtual machine
  ansible.builtin.command:
    cmd: >-
      virt-install --import --name {{ homeassistant_vm_name }} --description "Home Assistant OS"
      --os-variant=generic --ram=4096 --vcpus=2
      --disk {{ homeassistant_hassos_host_vm_storage }}/{{ homeassistant_vm_name }}.qcow2,bus=sata
      --network bridge=br0
      --graphics none --boot uefi
    creates: /var/lib/libvirt/qemu/nvram/{{ homeassistant_vm_name }}_VARS.fd
  when: homeassistant_vm_exists is not defined

- name: Dump vm xml
  ansible.builtin.command:
    cmd: virsh dumpxml {{ homeassistant_vm_name }}
  register: homeassistant_vm_xml
  changed_when: false

- name: Find vm mac from xml
  vars:
    homeassistant_pattern: mac address='(.{17})'
  ansible.builtin.set_fact:
    homeassistant_vm_mac: "{{ homeassistant_vm_xml.stdout_lines | regex_search(homeassistant_pattern, '\\1') }}"

- name: Autostart vm
  ansible.builtin.command:
    cmd: virsh autostart {{ homeassistant_vm_name }}
  args:
    creates: /etc/libvirt/qemu/autostart/{{ homeassistant_vm_name }}.xml
  when: homeassistant_vminfo.stdout_lines | regex_search("shut off")
