- name: Get infos on the traefik containers
  community.docker.docker_container_info:
    name: "{{ item }}"
  register: traefik_docker_status
  loop:
    - traefik
    - docker_proxy

- name: Does traefik container exist?
  ansible.builtin.set_fact:
    traefik_exists: true
  when: traefik_docker_status.results[0].exists

- name: Does docker proxy container exist?
  ansible.builtin.set_fact:
    traefik_docker_proxy_exists: true
  when: traefik_docker_status.results[1].exists

- name: Is traefik container running?
  ansible.builtin.set_fact:
    traefik_running: true
  when: traefik_exists is defined and traefik_docker_status.results[0].container['State']['Running']

- name: Is docker proxy container running?
  ansible.builtin.set_fact:
    traefik_docker_proxy_running: true
  when: traefik_docker_proxy_exists is defined and traefik_docker_status.results[1].container['State']['Running']
