- name: Create folders
  file:
    path: "{{ app_data_dir }}/traefik/{{ item }}/conf/"
    state: directory
    recurse: yes
    mode: 0755
  with_items:
    - internal
    - public

- name: Install the traefik config files
  template:
    src: "{{ item }}"
    dest: "{{ app_data_dir }}/traefik/{{ item.split('/')[-2] }}/conf/{{ item | basename | regex_replace('.j2$', '') }}"
    mode: 0644
  when: (item | basename).split('.')[0] in web_applications
  with_fileglob:
    - templates/internal/*.j2
    - templates/public/*.j2
  notify:
    - restart traefik internal
    - restart traefik public
  register: traefik_config

- name: Create install directory
  file:
    path: /opt/traefik
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Create config directory
  file:
    path: /opt/traefik/traefik/
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Create file provider directory
  file:
    path: /opt/traefik/traefik/conf
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: "{{ traefik_install_dir }}/docker-compose.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart traefik
  become: true

- name: Install config
  template:
    src: files/traefik.yml
    dest: /opt/traefik/traefik/traefik.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart traefik
  become: true

- name: Install file provider
  template:
    src: files/file-provider-main.yml
    dest: /opt/traefik/traefik/conf/main.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart traefik
  become: true

# - name: Install homeassistant provider
#   template:
#     src: files/file-provider-homeassistant.yml
#     dest: /opt/traefik/traefik/conf/homeassistant.yml
#     mode: "{{ docker_compose_file_mask }}"
#     owner: "{{ docker_user.name }}"
#   notify: restart traefik
#   when: traefik_provider_homeassistant
#   become: true

- name: Install plex provider
  template:
    src: files/file-provider-plex.yml
    dest: /opt/traefik/traefik/conf/plex.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart traefik
  when: traefik_provider_plex
  become: true

- name: logrotate config
  template:
    src: files/logrotate.conf
    dest: /etc/logrotate.d/traefik
    mode: "0600"
  become: true

- name: Check for nginx config
  stat:
    path: "{{ traefik_config_dir }}/nginx.conf"
  register: nginx_file
  become: true

- name: Create nginx config, if it doesn't exist already
  template:
    src: files/nginx.conf
    dest: "{{ traefik_config_dir }}/nginx.conf"
    mode: "0600"
  when: not nginx_file.stat.exists
  notify: restart traefik
  become: true
