- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true
  loop: "{{ traefik_dirs }}"

- name: Install the traefik config files
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ traefik_config_dir }}/config/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_file_mask }}"
  when: (item | basename).split('.')[0] in hostvars['localhost'].web_applications
  with_fileglob:
    - files/*.j2
  notify:
    - restart traefik
  register: traefik_config
  become: true

- name: Install config
  ansible.builtin.template:
    src: files/traefik.yml.j2
    dest: "{{ traefik_config_dir }}/traefik.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  notify: restart traefik
  become: true

- name: Install file provider
  ansible.builtin.template:
    src: files/file-provider-main.yml
    dest: "{{ traefik_config_dir }}/config/main.yml"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  notify: restart traefik
  become: true

- name: Logrotate config
  ansible.builtin.template:
    src: files/logrotate.conf
    dest: /etc/logrotate.d/traefik
    mode: 0600
  become: true

- name: Check for nginx config
  ansible.builtin.stat:
    path: "{{ traefik_install_dir }}/nginx.conf"
  register: nginx_file
  become: true

- name: Check for acme.json
  ansible.builtin.stat:
    path: "{{ traefik_config_dir }}/acme.json"
  register: acme_file
  become: true

- name: Create nginx config, if it doesn't exist already
  ansible.builtin.template:
    src: files/nginx.conf
    dest: "{{ traefik_install_dir }}/nginx.conf"
    mode: 0600
  when: not nginx_file.stat.exists
  notify: restart traefik
  become: true

- name: Force permissions for nginx.conf
  ansible.builtin.file:
    dest: "{{ traefik_install_dir }}/nginx.conf"
    mode: 0600
  become: true

- name: Force permissions for acme.json
  ansible.builtin.file:
    dest: "{{ traefik_config_dir }}/acme.json"
    mode: 0600
  become: true
  when: (acme_file.stat.exists) and (acme_file.stat.mode != "0600")
