- name: Create network
  docker_network:
    name: traefik
    internal: true
  become: true

- name: Create install directory
  file:
    path: /opt/traefik
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Create config directory
  file:
    path: /opt/traefik/traefik/
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Create file provider directory
  file:
    path: /opt/traefik/traefik/conf
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/traefik/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart traefik
  become: true

- name: Install config
  template:
    src: files/traefik.yml
    dest: /opt/traefik/traefik/traefik.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  notify: restart traefik
  become: true

# - name: Install file provider
#   template:
#     src: files/file-provider-main.yml
#     dest: /opt/traefik/traefik/conf/main.yml
#     mode: "{{ docker_compose_file_mask }}"
#     owner: "{{ docker_user.name }}"
#   notify: restart traefik
#   become: true

# - name: Install homeassistant provider
#   template:
#     src: files/file-provider-homeassistant.yml
#     dest: /opt/traefik/traefik/conf/homeassistant.yml
#     mode: "{{ docker_compose_file_mask }}"
#     owner: "{{ docker_user.name }}"
#   notify: restart traefik
#   when: traefik_provider_homeassistant
#   become: true

- name: Check for nginx config
  stat:
    path: /opt/traefik/nginx.conf
  register: nginx_file
  become: true

- name: Create nginx config, if it doesn't exist already
  template:
    src: files/nginx.conf
    dest: /opt/traefik/nginx.conf
    mode: "0600"
  when: not nginx_file.stat.exists
  notify: restart traefik
  become: true
