- name: Include vault
  include_vars: vault.yml

- include_tasks: check_status.yml
  when: enable_traefik_public | default(false) or enable_traefik_internal | default(false)

# - include_tasks: list_services.yml
#   when: enable_traefik_public | default(false) or enable_traefik_internal | default(false)

- include_tasks: install_configs.yml
  when: enable_traefik_public | default(false) or enable_traefik_internal | default(false)

- include_tasks: networks.yml

- include_tasks: docker.yml
  when: enable_traefik_public | default(false) or enable_traefik_internal | default(false)
