- name: Include vault
  ansible.builtin.include_vars: vault.yml

- name: Include check_status.yml
  ansible.builtin.include_tasks: check_status.yml
  when: enable_traefik | default(false)

- name: Include install_configs.yml
  ansible.builtin.include_tasks: install_configs.yml
  when: enable_traefik | default(false)

- name: Include networks.yml
  ansible.builtin.include_tasks: networks.yml
  when: enable_traefik | default(false)

- name: Include docker.yml
  ansible.builtin.include_tasks: docker.yml
  when: enable_traefik | default(false)
