- name: Create traefik network
  when: enable_traefik | default(false)
  community.docker.docker_network:
    name: traefik
    state: present
  notify:
    - Restart traefik

- name: Create docker proxy network
  when: enable_docker_proxy | default(false)
  community.docker.docker_network:
    name: proxy_private
    state: present
    internal: true
  notify:
    - Restart docker proxy
