- name: Create traefik network
  when: enable_traefik | default(false)
  docker_network:
    name: traefik
    external: true
  notify:
    - restart traefik

- name: Create docker proxy network
  when: enable_docker_proxy | default(false)
  docker_network:
    name: proxy_private
    internal: true
  notify:
    - restart docker proxy
