- name: Include vault
  include_vars: vault.yml

- name: Create app directory
  file:
    path: "{{ item }}"
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  loop: "{{ nightscout_1_dirs }}"
  become: true

- name: Create install directory
  file:
    path: /opt/nightscout_1
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml.j2
    dest: /opt/nightscout_1/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  notify: restart nightscout_1
  become: true
