restic_rclone_version: 1.61.1
restic_version: 0.15.0
restic_overlay_version: v3.1.3.0

restic_architecture: "{% if ansible_architecture == 'armv7l' %}arm{% else %}amd64{% endif %}"
restic_rclone_architecture: "{% if ansible_architecture == 'armv7l' %}arm-v7{% else %}amd64{% endif %}"
restic_overlay_architecture: "{% if ansible_architecture == 'armv7l' %}armhf{% else %}x86_64{% endif %}"

restic_cron: 0 2 * * *
restic_repository: rest:http://0.0.0.0:8080/
restic_rclone_config_location: /config/rclone/rclone.conf
restic_rclone_serve_args: -vvv
restic_backup_args: --exclude /data/.cache --exclude /data/node_modules
restic_forget_args: --keep-last 2 --prune
restic_notifications: false
restic_apprise_backup_args: ""
restic_apprise_forget_args: ""
restic_apprise_title: Restic
restic_healthcheck_url: https://hc-ping.com/{{ restic_healthcheck_id }}
restic_config_directory: "{{ app_data_dir }}/restic/config"
restic_rclone_config_path: /opt/restic-rclone/config/rclone.conf

restic_password: "{{ vault_restic_password }}"
restic_rclone_remote_name: "{{ vault_rclone_remote_name }}"
restic_rclone_remote_type: "{{ vault_rclone_remote_type }}"
restic_rclone_token: "{{ vault_rclone_token }}"
restic_rclone_remote_location: "{{ vault_rclone_remote_location }}"
restic_healthcheck_id: "{{ vault_restic_healthcheck_id }}"
