version: "3"

services:
  vaultwarden:
    image: vaultwarden/server:1.25.2
    restart: unless-stopped
    user: "{{ docker_user.id }}:{{ docker_user.id }}"
    volumes:
      - "{{ vaultwarden_data_dir }}/:/data"
    depends_on:
      - db
    dns: 1.1.1.1
    labels:
      - traefik.enable=true

      - traefik.http.routers.vaultwarden-ui.rule=Host(`vaultwarden.{{ host }}`)
      - traefik.http.routers.vaultwarden-ui.service=vaultwarden-ui
      - traefik.http.services.vaultwarden-ui.loadbalancer.server.port=80

      - traefik.http.routers.vaultwarden-websocket.rule=Host(`vaultwarden.{{ host }}`) && Path(`/notifications/hub`)
      - traefik.http.routers.vaultwarden-websocket.service=vaultwarden-websocket
      - traefik.http.services.vaultwarden-websocket.loadbalancer.server.port=3012

      - traefik.http.middlewares.vaultwarden-ratelimit.ratelimit.average=5
      - traefik.http.middlewares.vaultwarden-ratelimit.ratelimit.burst=1000
      - traefik.http.middlewares.vaultwarden-compress.compress=true

      - traefik.http.routers.vaultwarden-ui.middlewares=vaultwarden-ratelimit,vaultwarden-compress
      - traefik.http.routers.vaultwarden-websocket.middlewares=vaultwarden-ratelimit,vaultwarden-compress
    environment:
      - SIGNUPS_ALLOWED=true
      - DOMAIN=https://vaultwarden.{{ host }}
      - SHOW_PASSWORD_HINT=false
      - DATABASE_URL=postgres://vaultwarden:{{ vaultwarden_database_password }}@db/vaultwarden
      - INVITATIONS_ALLOWED=true
      - ROCKET_WORKERS={{ ansible_processor_nproc // 2 }}
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN={{ vaultwarden_admin_token }}
      - YUBICO_CLIENT_ID={{ vaultwarden_yubico_client_id }}
      - YUBICO_SECRET_KEY={{ vaultwarden_yubico_secret_key }}
    networks:
      - default
      - traefik

  db:
    image: postgres:14.5
    restart: unless-stopped
    volumes:
      - "{{ vaultwarden_db_dir }}/:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD={{ vaultwarden_database_password }}
      - POSTGRES_USER=vaultwarden

networks:
  traefik:
    external: true
