- name: Include variables
  ansible.builtin.include_vars:
    file: defaults/meta.yml

- name: Include vault
  ansible.builtin.include_vars: vault.yml

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  loop: "{{ wireguard_dirs }}"
  become: true
  when: host_enable_wireguard | default(false)

- name: Make sure the wireguard container is created and running
  when: host_enable_wireguard | default(false)
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: lscr.io/linuxserver/wireguard:{{ wireguard_version }}
    pull: true
    privileged: true
    capabilities:
      - NET_ADMIN
      # - SYS_MODULE  # we do not sys module for alpine Linux where wireguard is a part of kernel
    env:
      TZ: "{{ timezone }}"
      PUID: "{{ docker_user.id }}"
      PGID: "{{ docker_user.id }}"
      SERVERURL: "{{ host_wireguard_server_url }}"
      SERVERPORT: "{{ host_wireguard_server_port }}"
      PEERS: "{{ host_wireguard_peers }}"
      PEERDNS: 8.8.8.8
      INTERNAL_SUBNET: 10.3.33.0
      INTERFACE: wg0
      ALLOWEDIPS: 0.0.0.0/0
      # PERSISTENTKEEPALIVE_PEERS:  # optional
      LOG_CONFS: "true"  # to see QR codes in docker logs
    ports:
      - "{{ host_wireguard_server_port }}:{{ host_wireguard_server_port }}/udp"
    hostname: "{{ host_wireguard_hostname }}"
    state: started
    volumes:
      - "{{ wireguard_config_dir }}:/config"
      # - /lib/modules:/lib/modules  # we do not sys module for alpine Linux where wireguard is a part of kernel
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
    restart_policy: unless-stopped
  become: true
