- name: Include vault
  ansible.builtin.include_vars: vault.yml

- name: Install wireguard tools
  ansible.builtin.package:
    name: "{{ item }}"
  become: true
  loop:
    - wireguard-tools
    - qrencode

- name: Wireguard server config
  become: true
  notify: Restart wireguard
  block:
    - name: Create peer list
      vars:
        public_key: wireguard_client_{{ "{:02}".format(item | int) }}_public_key
        allowed_ips: wireguard_client_{{ "{:02}".format(item | int) }}_cidr
        peer: |
          [Peer]
          PublicKey = {{ lookup("vars", public_key) }}
          AllowedIPs = {{ lookup("vars", allowed_ips) }}
      ansible.builtin.set_fact:
        peer_list: >
          {{ peer_list | default("") }} {{ peer }}
      with_sequence: start=2 count=13
    - name: Generate server config
      ansible.builtin.template:
        src: files/server.conf
        dest: /etc/wireguard/wg0.conf
        mode: "0600"
        backup: true

- name: Wireguard client config
  vars:
    cidr: wireguard_client_{{ "{:02}".format(item | int) }}_cidr
    private_key: wireguard_client_{{ "{:02}".format(item | int) }}_private_key
    wireguard_client_cidr: "{{ lookup('vars', cidr) }}"
    wireguard_client_private_key: "{{ lookup('vars', private_key) }}"
  ansible.builtin.template:
    src: files/client.conf
    dest: "{{ home }}/wg_client_{{ '{:02}'.format(item | int) }}.conf"
    mode: "0600"
  with_sequence: start=2 count=13
  become: true
  notify: Restart wireguard

- name: Enable wireguard
  ansible.builtin.service:
    name: wg-quick@wg0
    enabled: true
  become: true
