host_enable_syncthing: true

host_syncthing_networks:
  - name: traefik

host_syncthing_url: server-main-syncthing.local

host_server_syncthing_hostname: server-main-syncthing

host_syncthing_volumes:
  - "{{ syncthing_data_dir }}:/var/syncthing"
  - "{{ syncthing_backup_dir }}:/data"
  - "{{ media_dir }}/photos:/photos"
