# ethernet interface
# ethernet_interface: br0
# ethernet_interface: enp1s0
home_lan_interface: br0
home_lan_bridge: "{{ home_lan_interface }}"

ansible_become_pass: "{{ vault_ansible_become_pass }}"
ansible_user_first_run: root
ansible_pass_first_run: "{{ vault_ansible_become_pass }}"

app_data_root: /media/drive
media_root: /media/drive

host_local: mainsrv.local

private_ip: "{{ mainsrv.ip }}"

create_docker_iot_network: false
create_docker_dmz_network: false
create_docker_home_lan_network: false
