# ethernet interface
# docker_ethernet_interface: br0
# docker_ethernet_interface: enp1s0
home_lan_interface: br0
home_lan_bridge: "{{ home_lan_interface }}"

ansible_become_pass: "{{ vault_ansible_become_pass }}"
ansible_user_first_run: root
ansible_pass_first_run: "{{ vault_ansible_become_pass }}"

app_data_root: /media/drive
media_root: /media/drive

host_local: novosibirsk

private_ip: "{{ mainsrv.ip }}"

create_docker_iot_network: false
create_docker_dmz_network: false
create_docker_home_lan_network: false
create_docker_mariadb_network: false

security_ssh_port: "{{ ssh_port }}"
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
security_ssh_allowed_users:
  - "{{ user.name }}"
security_sshd_state: started
security_ssh_restart_handler_state: restarted
security_sudoers_passwordless:
  - "{{ user.name }}"
security_autoupdate_enabled: true
security_autoupdate_blacklist: []
security_autoupdate_reboot: true
security_autoupdate_reboot_time: 03:15
security_fail2ban_enabled: true
