- name: Ensure localisation files are available for locale {{ config_system_locale }}
  become: true
  community.general.locale_gen:
    name: "{{ config_system_locale }}"
    state: present

- name: Ensure localisation files are available for language {{ config_system_language }}
  become: true
  community.general.locale_gen:
    name: "{{ config_system_language }}"
    state: present

- name: Get current locale and language configuration
  ansible.builtin.command: localectl status
  register: system_locale_status
  changed_when: false

- name: Parse 'LANG' from current locale and language configuration
  ansible.builtin.set_fact:
    system_locale_lang: "{{ system_locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

- name: Parse 'LANGUAGE' from current locale and language configuration
  ansible.builtin.set_fact:
    system_locale_language: "{{ system_locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([system_locale_lang], true) | first }}"

- name: Configure locale and language
  become: true
  ansible.builtin.command: localectl set-locale LANG={{ config_system_locale }} LANGUAGE={{ config_system_language }}
  changed_when: system_locale_lang != config_system_locale or system_locale_language != config_system_language

- name: Update bashrc to set locale environment variables
  when: ansible_os_family == 'Debian'
  ansible.builtin.lineinfile:
    dest: "{{ home }}/.bashrc"
    line: "{{ item }}"
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ user }}"
    state: present
    insertafter: EOF
    create: true
  loop:
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US.UTF-8
    - export LC_ALL=en_US.UTF-8
