- name: Update
  include_tasks: update.yml
- name: Packages
  include_tasks: packages.yml
- name: SSH
  include_tasks: ssh.yml
- name: User
  include_tasks: user.yml
- name: Modify .bashrc
  include_tasks: bashrc.yml
