- name: Netplan
  ansible.builtin.include_tasks: netplan.yml
  when: install_netplan | default(false)
- name: Update
  ansible.builtin.include_tasks: update.yml
  when: update_packages | default(false)
- name: Packages
  ansible.builtin.include_tasks: packages.yml
  when: install_packages | default(false)
- name: Snap
  ansible.builtin.include_tasks: remove_snap.yml
  when: remove_snap | default(false)
- name: User
  ansible.builtin.include_tasks: user.yml
  when: create_user | default(false)
- name: SSH
  ansible.builtin.include_tasks: ssh.yml
  when: update_ssh | default(false)
- name: Modify .bashrc
  ansible.builtin.include_tasks: bashrc.yml
  when: modify_barhrc | default(false)
- name: set locale
  ansible.builtin.include_tasks: locale.yml
  when: set_locale | default(false)
