- name: Users
  ansible.builtin.include_tasks: users.yml
  when: system_create_users | default(false)
- name: Netplan
  ansible.builtin.include_tasks: netplan.yml
  when: system_install_netplan | default(false)
- name: Update
  ansible.builtin.include_tasks: update.yml
  when: system_update_packages | default(false)
- name: Packages
  ansible.builtin.include_tasks: packages.yml
  when: system_install_packages | default(false)
- name: Snap
  ansible.builtin.include_tasks: remove_snap.yml
  when: system_remove_snap | default(false)
- name: Set locale
  ansible.builtin.include_tasks: locale.yml
  when: ansible_os_family == 'Debian' and system_set_locale | default(false)
- name: Mount volumes
  ansible.builtin.include_tasks: mount.yml
  when: system_do_mount | default(false)
