- name: Create mount points
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
  loop: "{{ mounts | default([]) }}"
  become: true

- name: Do mounts
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.volume }}"
    fstype: ext4
    state: mounted
  loop: "{{ mounts | default([]) }}"
  become: true
