- name: Get wifi interface
  ansible.builtin.set_fact:
    wifi_interface: "{{ item }}"
  loop: "{{ ansible_facts.interfaces }}"
  when: item.startswith("wl")

- name: Get ethernet interface
  ansible.builtin.set_fact:
    ethernet_interface: "{{ item }}"
  loop: "{{ ansible_facts.interfaces }}"
  when: item.startswith("en") and "." not in item

- name: Configure wifi with netplan
  ansible.builtin.template:
    src: files/02-wifi.yaml.j2
    dest: /etc/netplan/02-wifi.yaml
    mode: "0644"
  notify: netplan generate config
  when: wifi_interface is defined and enable_wifi
  become: true

- name: Check files
  ansible.builtin.stat:
    path: "{{ item }}"
  register: bridge_files
  loop:
    - /etc/netplan/03-bridge.yaml
    - /etc/netplan/03-bridge.yaml.bak

- name: Backup config
  ansible.builtin.copy:
    src: /etc/netplan/03-bridge.yaml
    dest: /etc/netplan/03-bridge.yaml.bak
    mode: "0644"
    remote_src: true
  when: bridge_files.results[0].stat.exists and not bridge_files.results[1].stat.exists
  become: true

- name: Configure netowrk bridge with netplan
  ansible.builtin.template:
    src: files/03-bridge.yaml.j2
    dest: /etc/netplan/03-bridge.yaml
    mode: "0644"
  notify: netplan generate config
  when: ethernet_interface is defined and ethernet_cidr is defined and enable_network_bridge
  become: true
