- name: Install OpenSSH for Debian
  ansible.builtin.package:
    name: openssh-server
  become: true
  when: ansible_os_family == 'Debian'

- name: Install OpenSSH for Arch
  ansible.builtin.package:
    name: openssh
  become: true
  when: ansible_os_family == 'Archlinux'

- name: Define context
  ansible.builtin.set_fact:
    user: "{{ user }}"
    enable_root: false

- name: SSH config
  ansible.builtin.template:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
    backup: true
    mode: "0644"
  become: true
  register: sshd_config

- name: Set up authorized keys
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ lookup('file', item) }}"
  loop:
    - ssh-keys/laptop.pub
    - ssh-keys/infra.pub

- name: Enable SSH
  ansible.builtin.service:
    name: sshd
    enabled: true
  become: true

- name: Restart SSH Daemon
  ansible.builtin.service:
    name: sshd
    state: reloaded
  when: sshd_config.changed
  become: true
