- name: Check port {{ ansible_port }}
  ansible.builtin.wait_for:
    port: "{{ ansible_port }}"
    state: started
    host: "{{ inventory_hostname }}"
    connect_timeout: 5
    timeout: 5
  delegate_to: localhost
  ignore_errors: true
  register: ssh_port_works

- name: Check port 22 with ssh key
  ansible.builtin.command: >
    ssh -o User={{ user.name }} -o ConnectTimeout=5 -o PreferredAuthentications=publickey -o PubkeyAuthentication=yes {{ inventory_hostname }} echo "Worked"
  delegate_to: localhost
  ignore_errors: true
  register: ssh_port_22_with_key_works
  when:
    - ssh_port_works is defined
    - ssh_port_works is failed

- name: Check port 22 with User={{ user.name }}
  ansible.builtin.command: sshpass -p{{ ansible_become_pass }} ssh -o User={{ user.name }} \
               -o ConnectTimeout=5 -o PreferredAuthentications=password -o PubkeyAuthentication=no {{ inventory_hostname }} echo "Worked"
  delegate_to: localhost
  ignore_errors: true
  register: ssh_port_22_with_user_works
  when:
    - ssh_port_22_with_key_works is defined
    - ssh_port_22_with_key_works is failed

- name: Check port 22 with User={{ ansible_user_first_run }}
  ansible.builtin.command: sshpass -p{{ ansible_pass_first_run }} ssh -o User={{ ansible_user_first_run }} \
               -o ConnectTimeout=5 -o PreferredAuthentications=password -o PubkeyAuthentication=no {{ inventory_hostname }} echo "Worked"
  delegate_to: localhost
  ignore_errors: true
  register: ssh_port_22_user_first_run
  when:
    - ssh_port_22_with_user_works is defined
    - ssh_port_22_with_user_works is failed

- name: Set SSH port to 22
  ansible.builtin.set_fact:
    ansible_port: 22
  when:
    ssh_port_22_with_key_works is defined and ssh_port_22_with_key_works is changed or
    ssh_port_22_with_user_works is defined and ssh_port_22_with_user_works is changed or
    ssh_port_22_user_first_run is defined and ssh_port_22_user_first_run is changed

- name: Set SSH user to ansible_user_first_run and password to ansible_pass_first_run
  ansible.builtin.set_fact:
    ansible_user: "{{ ansible_user_first_run }}"
    ansible_ssh_pass: "{{ ansible_pass_first_run }}"
  when:
    - ssh_port_22_user_first_run is defined
    - ssh_port_22_user_first_run is changed
