- name: Check port "{{ ansible_port }}"
  wait_for:
    port: "{{ ansible_port }}"
    state: started
    host: "{{ inventory_hostname }}"
    connect_timeout: 5
    timeout: 5
  delegate_to: localhost
  ignore_errors: true
  register: ssh_port_works

- name: Check port 22
  wait_for:
    port: 22
    state: started
    host: "{{ inventory_hostname }}"
    connect_timeout: 5
    timeout: 5
  delegate_to: localhost
  ignore_errors: true
  register: ssh_port_default
  when:
    - ssh_port_works is defined
    - ssh_port_works.state is undefined

- name: Set SSH port to 22
  set_fact:
    ansible_port: 22
  when: ssh_port_default.state is defined
