- name: Update and upgrade apt packages (Debian and Ubuntu)
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    upgrade: true
    autoremove: true
    update_cache: true
    purge: true
    autoclean: true
    clean: true
  become: true

- name: Update and upgrade apt packages (Alpine)
  when: ansible_os_family == 'Alpine'
  community.general.apk:
    upgrade: true
    update_cache: true
  become: true

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: system_reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
    msg: Rebooting due to a kernel update
  when: system_reboot_required_file.stat.exists
  become: true
