- name: Make user
  user:
    name: "{{ user }}"
    home: "{{ home }}"
    comment: "{{ userfullname }}"
    shell: /bin/bash
    system: true
  become: true

- name: Give user sudo access
  user:
    name: "{{ user }}"
    groups: "{{ 'sudo' if ansible_os_family == 'Debian' else 'wheel' }}"
    append: true
  become: true
