- name: Restart watchtower
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: started
    restart: true
  when: enable_watchtower | default(false) and watchtower_exists is defined and watchtower_running is defined
