---
# tasks file for zfs_extra
- name: Set Samba passwords for each user
  ansible.builtin.shell: |
    set -o pipefail
    printf '{{ item.password }}\n{{ item.password }}\n' | smbpasswd -a {{ item.name }}
  args:
    executable: /usr/bin/bash
  loop: "{{ users }}"
  tags: smbpasswd
  become: true
  register: zfs_extra_smbpasswd
  changed_when: "'Added user' in zfs_extra_smbpasswd.stdout"
  notify: Restart samba
