---
# tasks file for zfs_extra
- name: Set Samba passwords for each user
  ansible.builtin.shell: |
    set -o pipefail
    printf '{{ docker_user.password }}\n{{ docker_user.password }}\n' | smbpasswd -a {{ docker_user.name }}
  args:
    executable: /usr/bin/bash
  tags: smbpasswd
  become: true
  register: smbpasswd
  changed_when: "'Added user' in smbpasswd.stdout"
  notify: Restart samba
