- name: Restart plex
  community.docker.docker_container:
    name: plex
    state: started
    restart: true
  when: enable_plex | default(false) and plex_exists is defined and plex_running is defined
