homeassistant_create_bridge: false
homeassistant_create_directories: false
homeassistant_create_vm: true
homeassistant_download_image: true
homeassistant_prepare_kvm: false

homeassistant_root_dir: "{{ app_data_dir }}/homeassistant"
homeassistant_hassos_host_vm_storage: /opt/homeassistant/vm
homeassistant_hassos_version: 10.2
homeassistant_hassos_vm_img_url: >
  https://github.com/home-assistant/operating-system/releases/download/{{ homeassistant_hassos_version }}/haos_ova-{{ homeassistant_hassos_version }}.qcow2.xz
homeassistant_vm_name: server-hassio

homeassistant_dirs:
  - "{{ homeassistant_hassos_host_vm_storage }}"
  - "{{ homeassistant_root_dir }}"
