homeassistant_config_dir: "{{ app_data_dir }}/homeassistant/config"
homeassistant_vscode_config_dir: "{{ app_data_dir }}/homeassistant/.vscode"
homeassistant_install_dir: /opt/homeassistant
homeassistant_mariadb_dir: "{{ database_dir }}/mariadb/homeassistant"

homeassistant_dirs:
  - "{{ homeassistant_config_dir }}"
  - "{{ homeassistant_vscode_config_dir }}"
  - "{{ homeassistant_install_dir }}"
  - "{{ homeassistant_mariadb_dir }}"
