container_name: homeassistant  # noqa: var-naming[no-role-prefix]
homer_category: Home Assistant  # noqa: var-naming[no-role-prefix]
dashboard_name: Home Assistant  # noqa: var-naming[no-role-prefix]
logo: assets/tools/home-assistant.png  # noqa: var-naming[no-role-prefix]
subtitle: Main server  # noqa: var-naming[no-role-prefix]
tag: app  # noqa: var-naming[no-role-prefix]
url: https://homeassistant.{{ host }}  # noqa: var-naming[no-role-prefix]
