container_name: nightscout  # noqa: var-naming[no-role-prefix]
homer_category: Health  # noqa: var-naming[no-role-prefix]
dashboard_name: Nightscout  # noqa: var-naming[no-role-prefix]
logo: assets/tools/nightscout.png  # noqa: var-naming[no-role-prefix]
subtitle: Yuri  # noqa: var-naming[no-role-prefix]
tag: app  # noqa: var-naming[no-role-prefix]
url: https://ns.{{ host }}  # noqa: var-naming[no-role-prefix]
