# ethernet interface
# ethernet_interface: eth0
home_lan_interface: eth0

ansible_become_pass: "{{ vault_ansible_become_pass }}"
ansible_user_first_run: root
ansible_pass_first_run: "{{ vault_ansible_become_pass }}"

app_data_root: /mnt/storage
media_root: /mnt/storage

host_local: server-test.local

private_ip: "{{ server_test.ip }}"

create_docker_iot_network: false
create_docker_dmz_network: false
create_docker_home_lan_network: false
create_docker_mariadb_network: false
