- name: Remove docker-compose
  ansible.builtin.package:
    name: docker-compose
    state: absent
  become: true

- name: Install docker compose plugin
  ansible.builtin.package:
    name: docker-compose-plugin
    state: present
  become: true
