##### setup docker
- name: Install packages required by docker
  become: true
  ansible.builtin.apt:
    update_cache: true
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg-agent
      - software-properties-common
      - python3
      - python-is-python3
      - python3-docker

- name: Add docker GPG key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install docker
  become: true
  ansible.builtin.apt:
    update_cache: true
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

##### setup ansible <---> docker
- name: Install python dependencies
  become: true
  ansible.builtin.apt:
    update_cache: true
    state: present
    name: python3-pip

- name: Install 'Docker SDK for Python'
  become: false
  ansible.builtin.pip:
    name: docker
    state: present
