- name: Create docker group
  ansible.builtin.group:
    name: "{{ docker_user.name }}"
    state: present
    gid: "{{ docker_user.id }}"
  become: true

- name: Create docker user
  ansible.builtin.user:
    name: "{{ docker_user.name }}"
    uid: "{{ docker_user.id }}"
    group: "{{ docker_user.name }}"
    create_home: false
  become: true

- name: Add user to docker user group
  ansible.builtin.user:
    name: "{{ user }}"
    groups: "{{ docker_user.name }}"
    append: true
  become: true
