collections:
  - ansible.posix
  - community.general
  - community.docker

roles:
  - src: geerlingguy.docker
    version: 4.2.3
  - src: geerlingguy.ntp
    version: 2.3.1
  - src: chmduquesne.iptables_persistent
  - src: aklinkert.docker_cleanup
  - name: ansible-zfs
    src: https://github.com/mrlesmithjr/ansible-zfs
