- name: Do list services
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Run list services
      ansible.builtin.import_tasks: tasks/list_services.yml
      tags:
        - list_services

- name: Setup ssh port and user
  hosts: servers
  gather_facts: false
  tasks:
    - name: Detect ssh port and check first run user
      ansible.builtin.include_tasks: roles/system/tasks/ssh_port_and_user.yml

- name: Common system role
  hosts: servers
  roles:
    - system

- name: Install docker and docker cleanup
  hosts:
    - london.local
    - mainsrv.local
    - server-main.local
    - server-ns.local
    # - server-test.local
    - server-vpn.vashchenko.me
  roles:
    - role: docker
      tags: docker
      become: true
      when: enable_docker | default(false)
    - role: aklinkert.docker_cleanup
      tags: docker_cleanup
      when: ansible_os_family == 'Debian' and enable_docker_cleanup | default(false)
      become: true

- name: Install ntp
  hosts:
    - london.local
    - mainsrv.local
    - server-main.local
    - server-ns.local
    # - server-test.local
  roles:
    - role: geerlingguy.ntp
      tags: ntp
      become: true
      vars:
        ntp_timezone: "{{ timezone }}"
        ntp_manage_config: true
      when: enable_ntp | default(false)

- name: Server main specific tasks
  hosts:
    - server-main.local
  roles:
    - role: ansible-zfs
      tags: zfs
      become: true
      when: enable_zfs | default(false)
    - role: zfs_extra
      tags: zfs_extra
      when: enable_zfs | default(false)
    - role: traefik
      tags: traefik
      when: enable_traefik | default(false)
    - role: plex
      tags: plex
      become: true
      when: enable_plex | default(false)
    - role: deluge
      tags: deluge
      become: true
      when: enable_deluge | default(false)
    - role: homer
      tags: homer
      become: true
      vars:
        apps: "{{ hostvars['localhost'].web_applications }}"
      when: enable_homer | default(false)
    - role: homeassistant
      tags: homeassistant
      become: true
      when: enable_homeassistant | default(false)
    - role: vaultwarden
      tags: vaultwarden
      when: enable_vaultwarden | default(false) or enable_vaultwarden_backup | default(false)
    - role: restic
      tags: restic
      when: enable_restic | default(false)
    - role: nightscout
      tags: nightscout
      when: enable_nightscout | default(false)
    - role: syncthing
      tags: syncthing
      when: enable_syncthing | default(false)
    - role: duplicati
      tags: duplicati
      when: enable_duplicati | default(false)
    - role: watchtower
      tags: watchtower
      when: enable_watchtower | default(false)

- name: Server london specific tasks
  hosts:
    - london.local
  roles:
    - role: syncthing
      tags: syncthing
      become: true
      when: enable_syncthing | default(false)

- name: Servier vpn specific tasks
  hosts:
    - server-vpn.vashchenko.me
  roles:
    - role: wireguard
      tags: wireguard
      when: enable_wireguard | default(false)
