- name: Do list services
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Run list services
      ansible.builtin.import_tasks: tasks/list_services.yml
      tags:
        - list_services

- name: Common system role
  hosts: ongoing
  roles:
    - system

- name: Install docker and docker cleanup
  hosts:
    - ekaterinburg
    - novosibirsk
    - moscow
    - kazan
    # - server-test.local
    - novgorod
  roles:
    - role: docker
      tags: docker
      become: true
      when: enable_docker | default(false)
    - role: aklinkert.docker_cleanup
      tags: docker_cleanup
      when: ansible_os_family == 'Debian' and enable_docker_cleanup | default(false)
      become: true

- name: Install ntp
  hosts:
    - ekaterinburg
    - novosibirsk
    - moscow
    - kazan
    # - server-test.local
  roles:
    - role: geerlingguy.ntp
      tags: ntp
      become: true
      vars:
        ntp_timezone: "{{ timezone }}"
        ntp_manage_config: true
      when: enable_ntp | default(false)

- name: Install security
  hosts:
    - ekaterinburg
    - kazan
    - moscow
    - novosibirsk
    # - server-test.local
  roles:
    - role: geerlingguy.security
      tags: security
      become: true
      when: enable_security | default(false)

- name: Server main specific tasks
  hosts:
    - moscow
  roles:
    - role: ansible-zfs
      tags: zfs
      become: true
      when: enable_zfs | default(false)
    - role: zfs_extra
      tags: zfs_extra
      when: enable_zfs | default(false)
    - role: traefik
      tags: traefik
      when: enable_traefik | default(false)
    - role: mariadb
      tags: mariadb
      become: true
      when: enable_mariadb | default(false)
    - role: plex
      tags: plex
      become: true
      when: enable_plex | default(false)
    - role: deluge
      tags: deluge
      become: true
      when: enable_deluge | default(false)
    - role: homer
      tags: homer
      become: true
      vars:
        homer_apps: "{{ hostvars['localhost'].web_applications }}"
      when: enable_homer | default(false)
    - role: homeassistant
      tags: homeassistant
      become: true
      when: enable_homeassistant | default(false)
    - role: vaultwarden
      tags: vaultwarden
      when: enable_vaultwarden | default(false) or enable_vaultwarden_backup | default(false)
    - role: restic
      tags: restic
      when: enable_restic | default(false)
    - role: nightscout
      tags: nightscout
      when: enable_nightscout | default(false)
    - role: syncthing
      tags: syncthing
      when: enable_syncthing | default(false)
    - role: duplicati
      tags: duplicati
      when: enable_duplicati | default(false)
    - role: gotify
      tags: gotify
      when: enable_gotify | default(false)
    - role: watchtower
      tags: watchtower
      when: enable_watchtower | default(false)
    - role: nextcloud
      tags: nextcloud
      when: enable_nextcloud | default(false)

- name: Server london specific tasks
  hosts:
    - ekaterinburg
  roles:
    - role: syncthing
      tags: syncthing
      become: true
      when: enable_syncthing | default(false)

- name: Servier vpn specific tasks
  hosts:
    - novgorod
  roles:
    - role: wireguard
      tags: wireguard
      when: enable_wireguard | default(false)
