http:
  routers:
    router-homeassistant:
      rule: Host(`homeassistant.{{ host }}`)
      service: service-homeassistant
  services:
    service-homeassistant:
      loadBalancer:
        servers:
          - url: http://{{ homeassistant.ip }}:8123
