entryPoints:
  http:
    address: :80
  https:
    address: :443

providers:
  docker:
    endpoint: tcp://docker_proxy:2375
    exposedByDefault: false

http:
  routers:
    http-catchall:
      rule: HostRegexp(`{host:.+}`)
      entrypoints:
        - http
      middlewares:
        - redirect-to-https
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: false

api:
  dashboard: true

certificatesResolvers:
  letsEncrypt:
    acme:
      email: "{{ letsencrypt_email }}"
      storage: /etc/traefik/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: http
