entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
  web-secure:
    address: :443
    http:
      middlewares:
        - floc-block@file
        - compress@file
        - shenanigans@file
      tls:
        certresolver: letsEncrypt
        domains:
          - main: "{{ host }}"
            sans:
              - homeassistant.{{ host }}
              - vaultwarden.{{ host }}
  traefik:
    address: :8080

ping: {}

providers:
  docker:
    endpoint: tcp://docker_proxy:2375
    watch: true
    exposedByDefault: false
    network: traefik
  file:
    directory: /etc/traefik/conf

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  letsEncrypt:
    acme:
      email: "{{ letsencrypt_email }}"
      storage: /etc/traefik/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: web

serversTransport:
  insecureSkipVerify: true

metrics:
  prometheus:
    entryPoint: traefik

tls:
  options:
    default:
      minVersion: VersionTLS12

pilot:
  dashboard: false

accessLog:
  filePath: /var/log/traefik/access.log
  filters:
    statusCodes:
      - 400-600
