- name: Include vault
  ansible.builtin.include_vars: vault.yml

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_user.name }}"
    group: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  loop:
    - /opt/restic-rclone/config
    - "{{ restic_config_directory }}"
  become: true

- name: Install rclone config
  ansible.builtin.template:
    src: files/rclone.conf.j2
    dest: "{{ rclone_config_path }}"
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  become: true
  notify: rebuild and restart

- name: Install scripts and files
  ansible.builtin.copy:
    src: files/root
    dest: /opt/restic-rclone
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true
  notify: rebuild and restart

- name: Install Dockerfile
  ansible.builtin.template:
    src: files/Dockerfile
    dest: /opt/restic-rclone/Dockerfile
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  become: true

- name: Install compose file
  ansible.builtin.template:
    src: files/docker-compose.yml.j2
    dest: /opt/restic-rclone/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: docker-compose -f %s config
  become: true
  notify: rebuild and restart
