- name: Build container
  ansible.builtin.shell:
    chdir: /opt/restic-rclone
    cmd: "{{ docker_build_command }}"
  listen: rebuild and restart

- name: Restart restic-rclone
  ansible.builtin.shell:
    chdir: /opt/restic-rclone
    cmd: "{{ docker_update_command }}"
  listen: rebuild and restart
