- name: Include gotify
  ansible.builtin.include_tasks:
    file: "{{ role_path }}/../gotify/tasks/get_app_token.yml"
  vars:
    gotify_app_name: watchtower_gotify_app_name
    gotify_app_description: watchtower_gotify_app_description
