- name: Include variables
  ansible.builtin.include_vars:
    file: defaults/meta.yml

- name: Get info on the container {{ container_name }}
  community.docker.docker_container_info:
    name: "{{ container_name }}"
  register: watchtower_docker_status

- name: Does watchtower container exist?
  ansible.builtin.set_fact:
    watchtower_exists: true
  when: watchtower_docker_status.exists

- name: Is docker container running?
  ansible.builtin.set_fact:
    watchtower_running: true
  when: watchtower_exists is defined and watchtower_docker_status.container['State']['Running']

- name: Include gotify
  ansible.builtin.include_tasks:
    file: gotify.yml

- name: Make sure the watchtower container is created and running
  when: enable_watchtower | default(false)
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: containrrr/watchtower:{{ watchtower_version }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      TZ: "{{ timezone }}"
      WATCHTOWER_LABEL_ENABLE: "true"
      WATCHTOWER_NOTIFICATION_URL: gotify://gotify.{{ host }}/{{ gotify_application_token }}
    state: started
    labels:
      #
      # Watchtower
      com.centurylinklabs.watchtower.enable: "true"
    restart_policy: unless-stopped
